# Generated by Django 5.1.4 on 2025-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='enroll',
            field=models.DateField(auto_now_add=True),
        ),
    ]
