# Generated by Django 5.1.4 on 2025-04-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_studentmodel_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='enroll',
            new_name='date',
        ),
    ]
