# Generated by Django 5.1.4 on 2025-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_enroll_studentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
