# Generated by Django 5.1.4 on 2025-04-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_studentmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
